name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - uses: cypress-io/github-action@v6
        env:
          USERNAME: ${{ secrets.SMARTBEAR_TEST_USERNAME }}
          PASSWORD: ${{ secrets.SMARTBEAR_TEST_PASSWORD }}
          APP_BASE_URL: "http://secure.smartbearsoftware.com/samples/TestComplete12/WebOrders/"
        with: 
          command: npm run test:smoke

